# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, worlds!
    
    - id: modified
      uses: pheel/path-watcher-action@v1
      with:
        paths: 'src/**'
          
    - if: steps.modified.outputs.modified
      run: echo "Hey some change happened in one of your watched paths!"
